DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE cars CASCADE CONSTRAINTS;

CREATE TABLE customers (
	id NUMBER(2),
	name VARCHAR2(30),
	passwd VARCHAR2(30),
	CONSTRAINT pkCustomers PRIMARY KEY (id)
);
CREATE TABLE cars (
	id NUMBER(2),
	name VARCHAR2(30),
	price NUMBER(6),
	id_customer NUMBER(2),
	CONSTRAINT pkCars PRIMARY KEY (id),
	CONSTRAINT fkCars FOREIGN KEY (id_customer) REFERENCES customers(id)
);

INSERT INTO CUSTOMERS VALUES(1, 'Klammer','Klammer');
INSERT INTO CUSTOMERS VALUES(2, 'Mueller','Mueller');
INSERT INTO CUSTOMERS VALUES(3, 'Heinzer','Heinzer');

INSERT INTO CARS VALUES(1,'Ro 80',5000,NULL);
INSERT INTO CARS VALUES(2,'Puch 500',500,NULL);
INSERT INTO CARS VALUES(3,'Ford Edsel',33000,NULL);
INSERT INTO CARS VALUES(4,'DKW',5000,NULL);
INSERT INTO CARS VALUES(5,'Ford Cortina',1000,NULL);
INSERT INTO CARS VALUES(6,'Ford Capri',1300,NULL);
INSERT INTO CARS VALUES(7,'Opel Manta',1200,NULL);
INSERT INTO CARS VALUES(8,'Opel Admiral',7000,NULL);
INSERT INTO CARS VALUES(9,'Lada Taiga',200,NULL);
INSERT INTO CARS VALUES(10,'Simca 1200',600,NULL);
commit;
